### PR TITLE
[time-test-harness] JSRS migration

### PR DESCRIPTION
**Pull request by gabrieloliveira41**

### CODE REVIEW

**Comment by gabrieloliveira41** [comment]
Goals verified after changes (1 out of 1 goals total):

- MyDateTimeExpression
next week
January 13th to January 16th
April 2nd to May 3rd
next tuesday
tomorrow

All resulted in equal intents and equal IDE simulator results after migration comparing to before the migration

**Comment by gabrieloliveira41** [comment]
@kangawoo44 @abapayeViv could you review my PR, please?

**Review by abapayeViv — APPROVED** [review]
LGTM!

**Review by kangawoo44 — APPROVED** [review]
👍

**Pull request merged**
