### PR TITLE
Update items soon to be deprecated

### PR DESCRIPTION
**Pull request by bispodv**
These changes due to deprecation are being submitted due to some updates that were not made the last time

### CODE REVIEW

**Comment by adanis** [comment]
Hi @bispodv , I found macros that need to be converted in these two sample capsules as well:

- https://github.com/bixbydevelopers/capsule-samples-collection/tree/master/match-pattern
- https://github.com/bixbydevelopers/capsule-samples-collection/tree/master/preference-learning

Everything else looks good!

**Comment by bispodv** [comment]
Hello, @adanis. I have updated the PR with the changes for the capsules you mentioned above

**Review by adanis — APPROVED** [review]
Everything looks great! Thanks Daniel!

**Comment by abapayeViv** [comment]
LGTM!
@rogerkibbe Please merge this PR.

**Pull request merged**
