### PR TITLE
[audio] capsule JSRS migration

### PR DESCRIPTION
**Pull request by gabrieloliveira41**

### CODE REVIEW

**Comment by gabrieloliveira41** [comment]
the migration was successful i only needed to press the migration button and the only manual changed i did was in `resources\en\MeowResultView.view.bxb` cause it had a stage 2 deprecation 
`MeowResultView` before changes:
image
`MeowResultView` after changes:
image

**Comment by gabrieloliveira41** [comment]
Goal verified after changes (1 out of 1 goal total):
- 1 playMeow:
meow
say meow
play Cool Cat
play Kitten

All resulted in equal intents and equal IDE simulator results after migration comparing to before the migration

**Review by kangawoo44 — APPROVED** [review]
LGTM

**Review by abapayeViv — APPROVED** [review]
👍

**Pull request merged**
