### PR TITLE
[input-forms] JSRS Migration

### PR DESCRIPTION
**Pull request by fdsgusmao**

### CODE REVIEW

**Comment by fdsgusmao** [comment]
### Goals verified:

1. SubmitSurvey
    - Show survey

2. SelectPersonAutocomplete
    - Show auto complete

3. DurationPicker
    - Show duration picker

4. MultiSelectImage
    - Show multiple image picker

5. SelectPerson
    - Show selection picker

6. TimePicker
    - Show time picker

7. SelectImage
    - Show image picker

8. RequestPTO
    - Show calendar picker

9. DatePicker
    - Show date picker

**NO ERRORS:** Migration tool migrated the code successfully

**Comment by fdsgusmao** [comment]
@kangawoo44 

the only warning remaining is the same as in #93

image

**Review by kangawoo44 — APPROVED** [review]
LGTM

**Review by abapayeViv — APPROVED** [review]
👍

**Pull request merged**
