### PR TITLE
Add duration picker

### PR DESCRIPTION
**Pull request by johncolarusso**

### CODE REVIEW

**Comment by adanis** [comment]
:+1: lgtm

**Comment by adanis** [comment]
@rogerkibbe Can you unmerge this? We're waiting for 19L to go out with the actual component/documentation for this. :pray: please and thank you

**Comment by rogerkibbe** [comment]
Ooops too quick of a trigger finger. Process wise I think you should have been on the Reviewers list and not approved till things were ready. But I will fix and unmerge

**Comment by adanis** [comment]
That's fair, I think I should have left a comment. I mentioned it to John in passing, but in the future, I'll make sure to add it to the PR/YouTrack as well. Thanks @rogerkibbe !!

**Pull request merged**
