### PR TITLE
[bixby-views] JSRS migration - vcap 24459

### PR DESCRIPTION
**Pull request by gabrieloliveira41**

### CODE REVIEW

**Comment by gabrieloliveira41** [comment]
Goals verified after changes (28 out of 28 goals total):

- ShowFlowerCompoundCards

- ShowHotelImageCards

- ShowRideShareThumbnailCards

- ShowHotelPartitioned

- ShowFlowerThumbnailCards

- ShowRideShareCompoundCards

- ShowHotelSingleLine

- ShowHotelCarousel

- ShowProgressBar

- ShowRideShareImageCards

- ShowHotelCompoundCards

- ShowHotelImageList

- ShowFlowerCellAreas

- ShowHotelsHeaderImageArea

- ShowHotelsHeader

- ShowThumbnailAreas

- ShowHotelImageListOf

- ShowRideShareInputCells

- ShowHotelThumbnailCards

- ShowVideo

- ShowHotelHbox

- ShowHotelImage

- ShowRideShareMap

- ShowFlowerImageCards

- ShowHotelTitleCard

- ShowAttributionLink

- ShowFlowerCellCards

- ShowHotelTitleArea

All tests resulted in equal intents and equal IDE simulator results after migration comparing to before the migration

**Comment by gabrieloliveira41** [comment]
Hello @kangawoo44 @abapayeViv, could you review my PR, please?

**Comment by gabrieloliveira41** [comment]
there's only this warning left, one option is to either comment or delete that target cause since people will be testing on the IDE they will not be able to visualize on the TV
image

**Comment by kangawoo44** [comment]
> there's only this warning left, one option is to either comment or delete that target cause since people will be testing on the IDE they will not be able to visualize on the TV image

I think this warning is fine to keep. What do you think @abapayeViv ?

**Comment by abapayeViv** [comment]
I think that warning is fine. It gives important information which is temporary until Marketplace does support the TV target.

**Review by kangawoo44 — APPROVED** [review]
LGTM!

**Review by abapayeViv — APPROVED** [review]
👍

**Pull request merged**
